### PR TITLE
Feature/eve 1149

### PR DESCRIPTION
**Pull request by mcolzi**
Now the build start on CentOS8
https://eve-dev.devsca.com/github/scality/ring/#/builders/57/builds/2

Errors are on the dlm centos8 setup.sh

### CODE REVIEW

**Comment by bertranddemiddelaer** [comment]
This PR is based on the PR that updates buildbot, so I added a /wait

**Review by tcarmet — APPROVED** [review]
LGTM but indeed a rebase is needed to remove the content about the buildbot upgrade

**Comment by mcolzi** [comment]
Those commits have been integrated in another PR. Closing it

**Pull request closed without merging**
