### PR TITLE
EVE-1141:Add support for default value in prop in `doStepIf`

### PR DESCRIPTION
**Pull request by TeddyAndrieux**
`doStepIf` argument from step support property but it does not allow to
provide a default value for this property (`%(prop:my_prop:-false)`),
this commit add this support.

### CODE REVIEW

**Review by gdemonet — APPROVED** [review]
:+1:

**Comment by bertranddemiddelaer** [comment]
I am currently working on another branch to fix the eve builds, which are now broken. I think you can remove the changes you made to pip packages versions here and rebase from dev/1.7 when it is fixed.

**Pull request merged**
